import { NgModule } from '@angular/core';
import {MatNativeDateModule,
        MatDatepickerModule,
        MatIconModule,
        MatButtonModule,
        MatCheckboxModule,
        MatToolbarModule,
        MatCardModule,
        MatFormFieldModule,
        MatInputModule,
        MatRadioModule,
        MatListModule,
        MatTableModule,
        MatTabsModule,
        MatPaginatorModule,
        MatSelectModule,
        MatRippleModule} from '@angular/material';

import { FormsModule, ReactiveFormsModule } from '@angular/forms';

@NgModule({
imports: [
  MatNativeDateModule,
  MatDatepickerModule,
  MatIconModule,
  MatButtonModule,
  MatCheckboxModule,
  MatToolbarModule,
  FormsModule,
  MatCardModule,
  MatFormFieldModule,
  MatInputModule,
  MatListModule,
  MatRadioModule,
  MatTableModule,
  MatTabsModule,
  MatPaginatorModule,
  MatRippleModule,
  MatSelectModule
],
exports: [MatNativeDateModule,
  FormsModule,
  MatDatepickerModule,
  MatIconModule,
  MatButtonModule,
  MatCheckboxModule,
  MatToolbarModule,
  MatCardModule,
  MatFormFieldModule,
  MatInputModule,
  MatListModule,
  MatRadioModule,
  MatTableModule,
  MatTabsModule,
  MatPaginatorModule,
  MatRippleModule,
  MatSelectModule
],
})
export class MaterialModule { }
