import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import {
  MatButtonModule,
  MatCardModule,
  MatCheckboxModule,
  MatChipsModule,
  MatDatepickerModule,
  MatExpansionModule,
  MatFormFieldModule,
  MatIconModule,
  MatInputModule,
  MatListModule,
  MatMenuModule,
  MatNativeDateModule,
  MatPaginatorModule,
  MatProgressBarModule,
  MatRadioModule,
  MatRippleModule,
  MatSelectModule,
  MatSnackBarModule,
  MatTableModule,
  MatTabsModule,
  MatToolbarModule,
  MatTooltipModule,
  MatTreeModule,
  MatStepperModule,
} from '@angular/material';

@NgModule({
imports: [
  MatNativeDateModule,
  MatDatepickerModule,
  MatIconModule,
  MatButtonModule,
  MatCheckboxModule,
  MatToolbarModule,
  FormsModule,
  MatCardModule,
  MatFormFieldModule,
  MatInputModule,
  MatListModule,
  MatRadioModule,
  MatTableModule,
  MatTabsModule,
  MatPaginatorModule,
  MatRippleModule,
  MatMenuModule,
  MatSnackBarModule,
  MatSelectModule,
  MatExpansionModule,
  MatTooltipModule,
  MatStepperModule
],
exports: [MatNativeDateModule,
  FormsModule,
  MatDatepickerModule,
  MatIconModule,
  MatButtonModule,
  MatCheckboxModule,
  MatToolbarModule,
  MatCardModule,
  MatFormFieldModule,
  MatInputModule,
  MatListModule,
  MatRadioModule,
  MatTableModule,
  MatTabsModule,
  MatPaginatorModule,
  MatRippleModule,
  MatMenuModule,
  MatSnackBarModule,
  MatSelectModule,
  MatExpansionModule,
  MatProgressBarModule,
  MatChipsModule,
  MatTreeModule,
  MatTooltipModule,
  MatStepperModule
],
})
export class MaterialModule { }
